[package]
name = "gateway_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = {version="1.49.0", features=["full"]}
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
gateway_core = {path = "../gateway_core"}
reqwest = "0.13.2"
tower = "0.5.3"
tower-http = "0.6.8"
